@startuml media-catalogue

left to right direction

rectangle "<<service>> \n Media Catalogue Service" {
    (Browse Media) as browse_media
    (Media Full Text Search) as search_media
    (View Media Details) as view_media
    (Update Catalogue) as update_catalogue
    (Bulk Add Media Items) as bulk_add
    (Bulk Update Media Items) as bulk_update
    (Bulk Delete Media Items) as bulk_delete
    (Extract Media Search Trends) as export_search_trends
}

:   <<person>> \n Guest User: as guest_user
:    <<person>> \n AML Member: as aml_member
:                <<service>> \n Media Procurement Service: as media_procurement_service
:       <<service>> \n Reporting Service: as reporting_service

guest_user <|-r-- aml_member

browse_media <.l. search_media: <<extend>>
browse_media <-l- view_media: <<include>>
update_catalogue <.u. bulk_add: <<extend>>
update_catalogue <.u. bulk_update: <<extend>>
update_catalogue <.u. bulk_delete: <<extend>>

guest_user -- browse_media
guest_user -- search_media
guest_user -- view_media

update_catalogue -d- media_procurement_service
export_search_trends -d-- reporting_service

@enduml