@startuml manage-branch

left to right direction

rectangle "<<service>> \n Branch Management Service" {
    (Update branch opening hours) as update_opening_hours
    (Update shift schedule) as update_shift_schedule
    (View shift schedule) as view_shift_schedule
    (Search staff profiles) as search_profiles
    (View staff contact details) as view_staff_details
}

:      <<person>> \nBranch Manager: as branch_manager
:      <<person>> \nBranch Librarian: as branch_librarian


branch_manager -d- update_opening_hours
branch_manager -d- update_shift_schedule
branch_librarian -d- view_shift_schedule
branch_librarian -d- search_profiles
branch_librarian -d- view_staff_details

branch_librarian -l-|> branch_manager 

@enduml