@startuml

skinparam sequence {
    ActorBorderColor Black
    ActorBackgroundColor #A9DCDF
    ParticipantBorderColor Black
    ParticipantBackgroundColor #F8E1A0
    LifeLineBorderColor Black
    LifeLineBackgroundColor White
    NoteBorderColor Black
    NoteBackgroundColor #FEFECE
    ArrowColor Black
    ArrowThickness 1
    ActivationBorderColor Black
    ActivationBackgroundColor #B3E2CD
}

title UC-006: Payment Processing (Member)

actor AMLmember as Member
participant "Frontend Application" as FrontendApp
participant "MemberSubscriptionController" as SubscriptionController
participant "MemberSubscriptionLogic" as SubscriptionLogic
participant "MemberSubscriptionRepo" as SubscriptionRepo

Member -> FrontendApp: Query Subscription Plans
FrontendApp -> SubscriptionController: Subscription Plans Request
SubscriptionController -> SubscriptionLogic: Subscription Plans Payload
SubscriptionLogic -> SubscriptionRepo: Subscription Plans Query
SubscriptionRepo --> SubscriptionLogic: Subscription Plans Request
SubscriptionLogic --> SubscriptionController: Subscription Plans Payload
SubscriptionController --> FrontendApp: Subscription Plans Response 
FrontendApp --> Member: Subscription Plans List

Member -> FrontendApp: Select Subscription Type
FrontendApp -> SubscriptionController: Subscription Options Request
SubscriptionController -> SubscriptionLogic:  Subscription Options Payload
SubscriptionLogic -> SubscriptionRepo: Query Subscription 
SubscriptionRepo --> SubscriptionLogic: Subscription Options Result
SubscriptionLogic --> SubscriptionController: Subscription Options Payload
SubscriptionController --> FrontendApp: Subscription Options Response
FrontendApp --> Member: Display Subscription Options

alt Payment Success
    Member -> FrontendApp: Confirm Subscription and Payment
    FrontendApp -> SubscriptionController: Process Payment
    SubscriptionController -> SubscriptionLogic: Validate Payment
    SubscriptionLogic -> SubscriptionRepo: Audit Payment
    SubscriptionLogic --> SubscriptionController: Payment Successful
    SubscriptionController --> FrontendApp: Display Payment Successful 
    FrontendApp --> Member: Payment Successful Notification
else Payment Failure
    Member -> FrontendApp: Confirm Subscription and Payment
    FrontendApp -> SubscriptionController: Process Payment
    SubscriptionController -> SubscriptionLogic: Validate Payment
    SubscriptionLogic --> SubscriptionController: Payment Failed
    SubscriptionController --> FrontendApp: Display Payment Error
    FrontendApp --> Member: Payment Failed Notification
end

@enduml
