### Get media lists
GET http://localhost:3001/media

### Get a specific media
GET http://localhost:3001/media/4

### Create a new wishlist
POST http://localhost:5000/wishlists
Content-Type: application/json

{
    "wishlistName": "Research",
    "member_id": 6
}

### Add media to wishlist
POST http://localhost:5000/wishlists/18/media
Content-Type: application/json

{
    "media_id": 5 
}

### Remove media from a wishlist
DELETE http://localhost:5000/wishlists/4/media/2

### Delete a wishlist
DELETE http://localhost:5000/wishlists/1

### Get a specific wishlist with media details
GET http://localhost:5000/wishlists/3
