@startuml media-procurement

left to right direction

rectangle "<<service>> \n Media Procurement Service" {
    (Search wholesale media) as search_wholesale
    (Place wholesale order) as order_wholesale
    (Track wholesale orders) as track_wholesale_orders
    (Request wholesale media order) as submit_media_order_form
    (Approve media order request) as approve_media_order_form
    (Reject media order request) as reject_media_order_form
    (Contact media supplier) as contact_supplier
    (Search AML media) as search_aml
    (Request media transfer) as request_media_transfer
    (Accept media transfer request) as accept_media_transfer
    (Reject media transfer request) as reject_media_transfer
    (Transfer AML media) as transfer_media

}

:      <<person>>\nBranch Manager: as branch_manager
:       <<person>>\nPurchase Manager: as purchase_manager
:     <<ext. system>>\n Wholesale Supplier: as supplier_system
:         <<system>>\n AML delivery system: as delivery_system
:         <<service>>\n Notification service: as notification_service

branch_manager -d- search_aml
branch_manager -d- search_wholesale
branch_manager -d- submit_media_order_form
branch_manager -d- request_media_transfer
branch_manager -d- track_wholesale_orders

purchase_manager -d- search_aml
purchase_manager -d- search_wholesale
purchase_manager -d- order_wholesale
purchase_manager -d- contact_supplier
purchase_manager -d- approve_media_order_form
purchase_manager -d- reject_media_order_form
purchase_manager -d- accept_media_transfer
purchase_manager -d- reject_media_transfer
purchase_manager -d- transfer_media
purchase_manager -d- track_wholesale_orders

supplier_system -u- search_wholesale
supplier_system -u- order_wholesale
supplier_system -u- contact_supplier
supplier_system -u- track_wholesale_orders
supplier_system -u- approve_media_order_form

delivery_system -u- transfer_media
delivery_system -u- accept_media_transfer
delivery_system -r- notification_service

@endumla