### Retrieve susbscription type
GET http://localhost:5000/subscription
Content-Type: application/json

### 
POST  http://localhost:5000/subscription
Content-Type: application/json

{
  "member_id": 1,
  "subid": 2
}

###
PUT http://localhost:5000/subscription
Content-Type: application/json

{
  "member_id": 1,
  "subid": 3
}

###
DELETE http://localhost:5000/subscription
Content-Type: application/json

{
  "member_id": 1,
  "subid": 3
}
