@startuml
skinparam sequence {
    ActorBorderColor Black
    ActorBackgroundColor #A9DCDF
    ParticipantBorderColor Black
    ParticipantBackgroundColor #F8E1A0
    LifeLineBorderColor Black
    LifeLineBackgroundColor White
    NoteBorderColor Black
    NoteBackgroundColor #FEFECE
    ArrowColor Black
    ArrowThickness 1
    ActivationBorderColor Black
    ActivationBackgroundColor #B3E2CD
}

title UC-001: Permanent Scaling

participant LoadBalancer #F8E1A0
participant ServerInstances #F8E1A0
participant ReportingService #F8E1A0
participant AutoScalingService #F8E1A0
actor SysAdmin as "System Administrator" #A9DCDF
participant CloudManagementInterface #F8E1A0

== ALT - Quarterly Scaling ==
loop Every Quarter
	ReportingService -> ReportingService: Calculate expected growth
	ReportingService -> AutoScalingService: Provision Additional Resources
	AutoScalingService -> ServerInstances: Add New Instances
	AutoScalingService -> LoadBalancer: Update Configuration
end loop

== ALT - Scaling Up Failure ==
ReportingService -> ReportingService: Calculate expected growth
ReportingService -> AutoScalingService: Provision Additional Resources
AutoScalingService -> AutoScalingService: Failed To Provision Resources
AutoScalingService -> SysAdmin: Alert of Scaling Failure
SysAdmin -> CloudManagementInterface: Manually Adds Resources
SysAdmin -> LoadBalancer: Update Configuration

@enduml
